# Generated by Django 3.0.5 on 2020-04-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
