# Generated by Django 3.0.5 on 2020-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_shop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateField(default='2020-3-30'),
        ),
    ]
