# Generated by Django 3.0.5 on 2020-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20200505_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
