# Generated by Django 3.0.5 on 2020-05-05 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_auto_20200505_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
