# Generated by Django 3.0.5 on 2020-05-19 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_shop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(max_length=38),
        ),
        migrations.AlterField(
            model_name='shop',
            name='webid',
            field=models.CharField(max_length=35),
        ),
    ]
