# Generated by Django 3.0.5 on 2020-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20200519_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='pricepersqm',
            field=models.FloatField(max_length=40),
        ),
    ]
